# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-10 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20171009_2116'),
        ('course', '0002_auto_20171007_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='所属课程机构'),
        ),
    ]
