# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-14 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='视频时长(分钟数)'),
        ),
    ]
