# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-11 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20171009_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, upload_to='org/%Y/%m', verbose_name='头像'),
        ),
    ]
